# Copyright 2018-2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.2"

[buildpack]
id      = "org.cloudfoundry.java"
name    = "Cloud Foundry Java Buildpack"
version = "{{.Version}}"

[[order]]
group = [

### Order is strictly enforced
  { id = "org.cloudfoundry.archiveexpanding",          version = "1.0.93", optional = true },
  { id = "org.cloudfoundry.openjdk",                   version = "1.0.56" },
  { id = "org.cloudfoundry.buildsystem",               version = "1.0.126", optional = true },
  { id = "org.cloudfoundry.jvmapplication",            version = "1.0.78" },

### Order determines precedence
  { id = "org.cloudfoundry.tomcat",                    version = "1.1.18", optional = true },
  { id = "org.cloudfoundry.springboot",                version = "1.0.106", optional = true },
  { id = "org.cloudfoundry.distzip",                   version = "1.0.96", optional = true },
  { id = "org.cloudfoundry.procfile",                  version = "1.0.40", optional = true },

### Order does not matter
  { id = "org.cloudfoundry.azureapplicationinsights",  version = "1.0.99", optional = true },
  { id = "org.cloudfoundry.debug",                     version = "1.0.100", optional = true },
  { id = "org.cloudfoundry.googlestackdriver",         version = "1.0.50", optional = true },
  { id = "org.cloudfoundry.jdbc",                      version = "1.0.102", optional = true },
  { id = "org.cloudfoundry.jmx",                       version = "1.0.102", optional = true },
  { id = "org.cloudfoundry.springautoreconfiguration", version = "1.0.110", optional = true },
]

[stack]
id          = "io.buildpacks.stacks.bionic"
build-image = "cloudfoundry/build:base-cnb"
run-image   = "cloudfoundry/run:base-cnb"

[[metadata.dependencies]]
id      = "org.cloudfoundry.archiveexpanding"
name    = "Cloud Foundry Archive Expanding Buildpack"
version = "1.0.93"
uri     = "https://storage.googleapis.com/cnb-buildpacks/archive-expanding-cnb/org.cloudfoundry.archiveexpanding-1.0.93.tgz"
sha256  = "3d22e23bebbf4eea381e410223a2b818be4bb3a6681e072957216268c558848f"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/archive-expanding-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.azureapplicationinsights"
name    = "Cloud Foundry Azure Application Insights Buildpack"
version = "1.0.99"
uri     = "https://storage.googleapis.com/cnb-buildpacks/azure-application-insights-cnb/org.cloudfoundry.azureapplicationinsights-1.0.99.tgz"
sha256  = "87f7b05c99cfce61e7bcd1a98ed29567ad0641b04608a298d855461edd332b3e"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/azure-application-insights-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.buildsystem"
name    = "Cloud Foundry Build System Buildpack"
version = "1.0.126"
uri     = "https://storage.googleapis.com/cnb-buildpacks/build-system-cnb/org.cloudfoundry.buildsystem-1.0.126.tgz"
sha256  = "bea79c502df0cea7c0e7bcd5c41d47578b32b50a7732ab876b2ef5ede92b785c"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/build-system-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.debug"
name    = "Cloud Foundry Debug Buildpack"
version = "1.0.100"
uri     = "https://storage.googleapis.com/cnb-buildpacks/debug-cnb/org.cloudfoundry.debug-1.0.100.tgz"
sha256  = "73bf1262e1acf85606c3a8745477374cd75e26b936d2469d1305e9990a83aa4d"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/debug-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.distzip"
name    = "Cloud Foundry DistZip Buildpack"
version = "1.0.96"
uri     = "https://storage.googleapis.com/cnb-buildpacks/dist-zip-cnb/org.cloudfoundry.distzip-1.0.96.tgz"
sha256  = "8fc2d0e74dedab1e945aa7a27b1b882263c11409cc45ca11dbcae52a7f78455f"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/dist-zip-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.googlestackdriver"
name    = "Cloud Foundry Google Stackdriver Buildpack"
version = "1.0.50"
uri     = "https://storage.googleapis.com/cnb-buildpacks/google-stackdriver-cnb/org.cloudfoundry.googlestackdriver-1.0.50.tgz"
sha256  = "567ef4415f831ceaf8d1b07811e37ce3f06728911a756a0e51cef47904c7d7a7"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/google-stackdriver-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jdbc"
name    = "Cloud Foundry JDBC Buildpack"
version = "1.0.102"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jdbc-cnb/org.cloudfoundry.jdbc-1.0.102.tgz"
sha256  = "7f5bb85951c1d5005cdd76bbaaf8c3033c770c51b940371803236af3a1f6f7f7"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jdbc-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jmx"
name    = "Cloud Foundry JMX Buildpack"
version = "1.0.102"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jmx-cnb/org.cloudfoundry.jmx-1.0.102.tgz"
sha256  = "19c020e7304af052ea9da13cff5fd8cb817d2902f3fb2841775afbd97a7daf72"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jmx-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jvmapplication"
name    = "Cloud Foundry JVM Application Buildpack"
version = "1.0.78"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jvm-application-cnb/org.cloudfoundry.jvmapplication-1.0.78.tgz"
sha256  = "b59a6605e15636a21d91ae68551def98eb921b81fda3ad4b9341aacf4fa4c9be"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jvm-application-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.openjdk"
name    = "Cloud Foundry OpenJDK Buildpack"
version = "1.0.56"
uri     = "https://storage.googleapis.com/cnb-buildpacks/openjdk-cnb/org.cloudfoundry.openjdk-1.0.56.tgz"
sha256  = "f9f0e06ac94475b67fabc03d9b32a6d66d7a52d4e0c1f172e9c940f648d1fc1c"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/openjdk-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.procfile"
name    = "Cloud Foundry Procfile Buildpack"
version = "1.0.40"
uri     = "https://storage.googleapis.com/cnb-buildpacks/procfile-cnb/org.cloudfoundry.procfile-1.0.40.tgz"
sha256  = "9987bdb346b19fad70f4a9c3d9847620d8a8b1d9e52c03c363931f15647a3107"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/procfile-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.springautoreconfiguration"
name    = "Cloud Foundry Spring Auto-reconfiguration Buildpack"
version = "1.0.110"
uri     = "https://storage.googleapis.com/cnb-buildpacks/spring-auto-reconfiguration-cnb/org.cloudfoundry.springautoreconfiguration-1.0.110.tgz"
sha256  = "fc3bcae97f17e2387d11412ea67fa1497b28c96cd97e9c069d091eee7c7c903e"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/spring-auto-reconfiguration-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.springboot"
name    = "Cloud Foundry Spring Boot Buildpack"
version = "1.0.106"
uri     = "https://storage.googleapis.com/cnb-buildpacks/spring-boot-cnb/org.cloudfoundry.springboot-1.0.106.tgz"
sha256  = "41beb953f7ba186f3d77573ddca49c75aa3a73f74e1520b00d07d46af0db06ad"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/spring-boot-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.tomcat"
name    = "Cloud Foundry Tomcat Buildpack"
version = "1.1.18"
uri     = "https://storage.googleapis.com/cnb-buildpacks/tomcat-cnb/org.cloudfoundry.tomcat-1.1.18.tgz"
sha256  = "eb8b1263172c6f903aa552e8cb39d788eff2be0dc16584bb5466ce1c3bce86c6"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/tomcat-cnb/blob/master/LICENSE"

[metadata]
include_files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "buildpack.toml",
]
