buildpacks = [
  { id = "org.cloudfoundry.archiveexpanding",          uri = "archive-expanding-cnb",           latest = true },
  { id = "org.cloudfoundry.azureapplicationinsights",  uri = "azure-application-insights-cnb",  latest = true },
  { id = "org.cloudfoundry.buildsystem",               uri = "build-system-cnb",                latest = true },
  { id = "org.cloudfoundry.debug",                     uri = "debug-cnb",                       latest = true },
  { id = "org.cloudfoundry.distzip",                   uri = "dist-zip-cnb",                    latest = true },
  { id = "org.cloudfoundry.googlestackdriver",         uri = "google-stackdriver-cnb",          latest = true },
  { id = "org.cloudfoundry.jdbc",                      uri = "jdbc-cnb",                        latest = true },
  { id = "org.cloudfoundry.jmx",                       uri = "jmx-cnb",                         latest = true },
  { id = "org.cloudfoundry.jvmapplication",            uri = "jvm-application-cnb",             latest = true },
  { id = "org.cloudfoundry.openjdk",                   uri = "openjdk-cnb",                     latest = true },
  { id = "org.cloudfoundry.procfile",                  uri = "procfile-cnb",                    latest = true },
  { id = "org.cloudfoundry.springautoreconfiguration", uri = "spring-auto-reconfiguration-cnb", latest = true },
  { id = "org.cloudfoundry.springboot",                uri = "spring-boot-cnb",                 latest = true },
  { id = "org.cloudfoundry.tomcat",                    uri = "tomcat-cnb",                      latest = true },
]

[[groups]]
labels = [ "java" ]
buildpacks = [

### Order is strictly enforced
  { id = "org.cloudfoundry.archiveexpanding",          version = "latest", optional = true },
  { id = "org.cloudfoundry.openjdk",                   version = "latest" },
  { id = "org.cloudfoundry.buildsystem",               version = "latest", optional = true },
  { id = "org.cloudfoundry.jvmapplication",            version = "latest" },

### Order determines precedence
  { id = "org.cloudfoundry.tomcat",                    version = "latest", optional = true },
  { id = "org.cloudfoundry.springboot",                version = "latest", optional = true },
  { id = "org.cloudfoundry.distzip",                   version = "latest", optional = true },
  { id = "org.cloudfoundry.procfile",                  version = "latest", optional = true },

### Order does not matter
  { id = "org.cloudfoundry.azureapplicationinsights",  version = "latest", optional = true },
  { id = "org.cloudfoundry.debug",                     version = "latest", optional = true },
  { id = "org.cloudfoundry.googlestackdriver",         version = "latest", optional = true },
  { id = "org.cloudfoundry.jdbc",                      version = "latest", optional = true },
  { id = "org.cloudfoundry.jmx",                       version = "latest", optional = true },
  { id = "org.cloudfoundry.springautoreconfiguration", version = "latest", optional = true },
]

[stack]
id = "io.buildpacks.stacks.bionic"
build-image = "cnbs/build"
run-image   = "cnbs/run"
