# Copyright 2018-2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.2"

[buildpack]
id      = "org.cloudfoundry.java"
name    = "Cloud Foundry Java Buildpack"
version = "{{.Version}}"

[[order]]
group = [

### Order is strictly enforced
  { id = "org.cloudfoundry.openjdk",                   version = "1.0.60" },
  { id = "org.cloudfoundry.buildsystem",               version = "1.0.138", optional = true },

### Order determines precedence
  { id = "org.cloudfoundry.jvmapplication",            version = "1.0.86" },
  { id = "org.cloudfoundry.tomcat",                    version = "1.1.29", optional = true },
  { id = "org.cloudfoundry.springboot",                version = "1.0.116", optional = true },
  { id = "org.cloudfoundry.distzip",                   version = "1.0.104", optional = true },
  { id = "org.cloudfoundry.procfile",                  version = "1.0.44", optional = true },

### Order does not matter
  { id = "org.cloudfoundry.azureapplicationinsights",  version = "1.0.111", optional = true },
  { id = "org.cloudfoundry.debug",                     version = "1.0.110", optional = true },
  { id = "org.cloudfoundry.googlestackdriver",         version = "1.0.58", optional = true },
  { id = "org.cloudfoundry.jdbc",                      version = "1.0.113", optional = true },
  { id = "org.cloudfoundry.jmx",                       version = "1.0.111", optional = true },
  { id = "org.cloudfoundry.springautoreconfiguration", version = "1.0.117", optional = true },
]

[stack]
id          = "io.buildpacks.stacks.bionic"
build-image = "cloudfoundry/build:base-cnb"
run-image   = "cloudfoundry/run:base-cnb"

[[metadata.dependencies]]
id      = "org.cloudfoundry.azureapplicationinsights"
name    = "Cloud Foundry Azure Application Insights Buildpack"
version = "1.0.111"
uri     = "https://storage.googleapis.com/cnb-buildpacks/azure-application-insights-cnb/org.cloudfoundry.azureapplicationinsights-1.0.111.tgz"
sha256  = "171ab15e311cf49c01c2964386fdd34558cda5e0765f39f7890863a506df1d59"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/azure-application-insights-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.buildsystem"
name    = "Cloud Foundry Build System Buildpack"
version = "1.0.138"
uri     = "https://storage.googleapis.com/cnb-buildpacks/build-system-cnb/org.cloudfoundry.buildsystem-1.0.138.tgz"
sha256  = "f9a1d7785e697d689fe6c19e412e15fd2e6209b6db1b60f3bdd9263e18df30c0"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/build-system-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.debug"
name    = "Cloud Foundry Debug Buildpack"
version = "1.0.110"
uri     = "https://storage.googleapis.com/cnb-buildpacks/debug-cnb/org.cloudfoundry.debug-1.0.110.tgz"
sha256  = "64b34d3bd66a222a786f1fb548269e8aea027bcf54e398159da4b5b1e2fe6363"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/debug-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.distzip"
name    = "Cloud Foundry DistZip Buildpack"
version = "1.0.104"
uri     = "https://storage.googleapis.com/cnb-buildpacks/dist-zip-cnb/org.cloudfoundry.distzip-1.0.104.tgz"
sha256  = "f3b5d66ce48c226dd5c8f0c579f73670964b663680b4df7319f164ddb809641b"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/dist-zip-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.googlestackdriver"
name    = "Cloud Foundry Google Stackdriver Buildpack"
version = "1.0.58"
uri     = "https://storage.googleapis.com/cnb-buildpacks/google-stackdriver-cnb/org.cloudfoundry.googlestackdriver-1.0.58.tgz"
sha256  = "3f7652478c071dab5ef19a8bb6dd063a1bc0fb650a26816f1ee83f9dc85a3fb1"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/google-stackdriver-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jdbc"
name    = "Cloud Foundry JDBC Buildpack"
version = "1.0.113"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jdbc-cnb/org.cloudfoundry.jdbc-1.0.113.tgz"
sha256  = "10b890a26b38dbb16a6833123f36a9e8d8b680b7822ba2b02734bea6f2ebb225"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jdbc-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jmx"
name    = "Cloud Foundry JMX Buildpack"
version = "1.0.111"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jmx-cnb/org.cloudfoundry.jmx-1.0.111.tgz"
sha256  = "5f34c306ad48a52c92412d7b19478f707a67fd85901223fd097aa2cbb5ae3efc"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jmx-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jvmapplication"
name    = "Cloud Foundry JVM Application Buildpack"
version = "1.0.86"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jvm-application-cnb/org.cloudfoundry.jvmapplication-1.0.86.tgz"
sha256  = "061fd27a2256552ba4eba5c631cb4ad2f7a64ef5e349d91ca7dc7119f9956175"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jvm-application-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.openjdk"
name    = "Cloud Foundry OpenJDK Buildpack"
version = "1.0.60"
uri     = "https://storage.googleapis.com/cnb-buildpacks/openjdk-cnb/org.cloudfoundry.openjdk-1.0.60.tgz"
sha256  = "ef8ce55386f95551f3bec7ff3317637716aec253a62729afc2f0efb852b98206"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/openjdk-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.procfile"
name    = "Cloud Foundry Procfile Buildpack"
version = "1.0.44"
uri     = "https://storage.googleapis.com/cnb-buildpacks/procfile-cnb/org.cloudfoundry.procfile-1.0.44.tgz"
sha256  = "9b09edb08fcfccb4266b4ba3924a92bbf188bd0506770ff1c2c5fe2f68480d33"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/procfile-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.springautoreconfiguration"
name    = "Cloud Foundry Spring Auto-reconfiguration Buildpack"
version = "1.0.117"
uri     = "https://storage.googleapis.com/cnb-buildpacks/spring-auto-reconfiguration-cnb/org.cloudfoundry.springautoreconfiguration-1.0.117.tgz"
sha256  = "ee50bae950a0dfbbe4fc061c06cfa09f1980256263273ce7d442fef19b794849"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/spring-auto-reconfiguration-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.springboot"
name    = "Cloud Foundry Spring Boot Buildpack"
version = "1.0.116"
uri     = "https://storage.googleapis.com/cnb-buildpacks/spring-boot-cnb/org.cloudfoundry.springboot-1.0.116.tgz"
sha256  = "9421a4b600189c57cda7021fc98a85a65aa80886a4836aebe84552190092d52b"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/spring-boot-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.tomcat"
name    = "Cloud Foundry Tomcat Buildpack"
version = "1.1.29"
uri     = "https://storage.googleapis.com/cnb-buildpacks/tomcat-cnb/org.cloudfoundry.tomcat-1.1.29.tgz"
sha256  = "e1f02eb30b0c8f13f944454301427b28cb7e6718366a5c2f586747d00ae3148d"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/tomcat-cnb/blob/master/LICENSE"

[metadata]
include_files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "buildpack.toml",
]
