[[buildpacks]]
id = "org.cloudfoundry.buildsystem"
uri = "file://build-system-buildpack"

[[buildpacks]]
id = "org.cloudfoundry.jvmapplication"
uri = "file://jvm-application-buildpack"

[[buildpacks]]
id = "org.cloudfoundry.openjdk"
uri = "file://openjdk-buildpack"


[[groups]]

  [[groups.buildpacks]]
  id = "org.cloudfoundry.openjdk"
  version = "1.0.0-BUILD-SNAPSHOT"

  [[groups.buildpacks]]
  id = "org.cloudfoundry.buildsystem"
  version = "1.0.0-BUILD-SNAPSHOT"
  optional = true

  [[groups.buildpacks]]
  id = "org.cloudfoundry.jvmapplication"
  version = "1.0.0-BUILD-SNAPSHOT"
