# Copyright 2018-2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.2"

[buildpack]
id      = "org.cloudfoundry.java"
name    = "Cloud Foundry Java Buildpack"
version = "{{.Version}}"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[order]]
group = [

### Order is strictly enforced
  { id = "org.cloudfoundry.archiveexpanding",          version = "1.0.39", optional = true },
  { id = "org.cloudfoundry.openjdk",                   version = "1.0.19" },
  { id = "org.cloudfoundry.buildsystem",               version = "1.0.40", optional = true },
  { id = "org.cloudfoundry.jvmapplication",            version = "1.0.29" },

### Order determines precedence
  { id = "org.cloudfoundry.tomcat",                    version = "1.0.43", optional = true },
  { id = "org.cloudfoundry.springboot",                version = "1.0.33", optional = true },
  { id = "org.cloudfoundry.distzip",                   version = "1.0.35", optional = true },
  { id = "org.cloudfoundry.procfile",                  version = "1.0.13", optional = true },

### Order does not matter
  { id = "org.cloudfoundry.azureapplicationinsights",  version = "1.0.38", optional = true },
  { id = "org.cloudfoundry.debug",                     version = "1.0.38", optional = true },
  { id = "org.cloudfoundry.googlestackdriver",         version = "1.0.22", optional = true },
  { id = "org.cloudfoundry.jdbc",                      version = "1.0.35", optional = true },
  { id = "org.cloudfoundry.jmx",                       version = "1.0.36", optional = true },
  { id = "org.cloudfoundry.springautoreconfiguration", version = "1.0.41", optional = true },
]

[[metadata.dependencies]]
id      = "org.cloudfoundry.archiveexpanding"
name    = "Cloud Foundry Archive Expanding Buildpack"
version = "1.0.39"
uri     = "https://storage.googleapis.com/cnb-buildpacks/archive-expanding-cnb/org.cloudfoundry.archiveexpanding-1.0.39.tgz"
sha256  = "626af1afbea1d2268961a62d8f6a64ebd1a8990266d15a941a322ff351afd66a"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/archive-expanding-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.azureapplicationinsights"
name    = "Cloud Foundry Azure Application Insights Buildpack"
version = "1.0.38"
uri     = "https://storage.googleapis.com/cnb-buildpacks/azure-application-insights-cnb/org.cloudfoundry.azureapplicationinsights-1.0.38.tgz"
sha256  = "b573deeaa87bdce531e2f70cd1077c570fab2d6124e43f63e0cfb221483151d5"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/azure-application-insights-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.buildsystem"
name    = "Cloud Foundry Build System Buildpack"
version = "1.0.40"
uri     = "https://storage.googleapis.com/cnb-buildpacks/build-system-cnb/org.cloudfoundry.buildsystem-1.0.40.tgz"
sha256  = "d4184e93ea8996fc47b79f288a9890b01a403f35af839bbb8a49f8873e6140ba"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/build-system-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.debug"
name    = "Cloud Foundry Debug Buildpack"
version = "1.0.38"
uri     = "https://storage.googleapis.com/cnb-buildpacks/debug-cnb/org.cloudfoundry.debug-1.0.38.tgz"
sha256  = "d29677e701d8864c95c6859e5e33c442de3705eff362c276fd97b53dc7de695b"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/debug-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.distzip"
name    = "Cloud Foundry DistZip Buildpack"
version = "1.0.35"
uri     = "https://storage.googleapis.com/cnb-buildpacks/dist-zip-cnb/org.cloudfoundry.distzip-1.0.35.tgz"
sha256  = "987fc8cc7a89a6270932613ee8a02b099593a7dc106ed65da8686934e1a0472d"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/dist-zip-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.googlestackdriver"
name    = "Cloud Foundry Google Stackdriver Buildpack"
version = "1.0.22"
uri     = "https://storage.googleapis.com/cnb-buildpacks/google-stackdriver-cnb/org.cloudfoundry.googlestackdriver-1.0.22.tgz"
sha256  = "dfe075c4fa5a4a1d4789df7ab9853223837cafad20c9c48a7bef8d9aa4fcfd9a"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/google-stackdriver-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jdbc"
name    = "Cloud Foundry JDBC Buildpack"
version = "1.0.35"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jdbc-cnb/org.cloudfoundry.jdbc-1.0.35.tgz"
sha256  = "c55b9923cef157a79caee1773b94d6c2d04e0a3801afd4dda44876ead188154c"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jdbc-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jmx"
name    = "Cloud Foundry JMX Buildpack"
version = "1.0.36"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jmx-cnb/org.cloudfoundry.jmx-1.0.36.tgz"
sha256  = "f646d1df22174ebfa19104fe737095b6113d60cf921c6994f240910b50182ae7"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jmx-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jvmapplication"
name    = "Cloud Foundry JVM Application Buildpack"
version = "1.0.29"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jvm-application-cnb/org.cloudfoundry.jvmapplication-1.0.29.tgz"
sha256  = "32b69a4ec8b8612666341a1b73651439abf4cddc8783b5db46c081d7cb23436f"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jvm-application-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.openjdk"
name    = "Cloud Foundry OpenJDK Buildpack"
version = "1.0.19"
uri     = "https://storage.googleapis.com/cnb-buildpacks/openjdk-cnb/org.cloudfoundry.openjdk-1.0.19.tgz"
sha256  = "f2d4ff66ebd442488a0790b7e83794c55e4f5e0df6eba80adfd38f8d2b329a55"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/openjdk-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.procfile"
name    = "Cloud Foundry Procfile Buildpack"
version = "1.0.13"
uri     = "https://storage.googleapis.com/cnb-buildpacks/procfile-cnb/org.cloudfoundry.procfile-1.0.13.tgz"
sha256  = "041c93197b04fa320d1880bd70ca275a3fd322728231d29a77fd568bab3237da"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/procfile-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.springautoreconfiguration"
name    = "Cloud Foundry Spring Auto-reconfiguration Buildpack"
version = "1.0.41"
uri     = "https://storage.googleapis.com/cnb-buildpacks/spring-auto-reconfiguration-cnb/org.cloudfoundry.springautoreconfiguration-1.0.41.tgz"
sha256  = "9e782cef177378e292fdec21099c222546ca9f13de52143f6d519795545dd608"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/spring-auto-reconfiguration-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.springboot"
name    = "Cloud Foundry Spring Boot Buildpack"
version = "1.0.33"
uri     = "https://storage.googleapis.com/cnb-buildpacks/spring-boot-cnb/org.cloudfoundry.springboot-1.0.33.tgz"
sha256  = "4cab78749ba6c878a1a99d20642e89b7b7c4fcb2cc2bd69cee2f2efdd116c83e"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/spring-boot-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.tomcat"
name    = "Cloud Foundry Tomcat Buildpack"
version = "1.0.43"
uri     = "https://storage.googleapis.com/cnb-buildpacks/tomcat-cnb/org.cloudfoundry.tomcat-1.0.43.tgz"
sha256  = "849ef7287d43b6104fec5d307250909f6c340c191104dde974ea6583aa136262"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/tomcat-cnb/blob/master/LICENSE"

[metadata]
include_files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "buildpack.toml",
]
