# Copyright 2018-2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.2"

[buildpack]
id      = "org.cloudfoundry.java"
name    = "Cloud Foundry Java Buildpack"
version = "{{.Version}}"

[[order]]
group = [

### Order is strictly enforced
  { id = "org.cloudfoundry.openjdk",                   version = "1.0.61" },
  { id = "org.cloudfoundry.buildsystem",               version = "1.0.143", optional = true },

### Order determines precedence
  { id = "org.cloudfoundry.jvmapplication",            version = "1.0.87" },
  { id = "org.cloudfoundry.tomcat",                    version = "1.1.33", optional = true },
  { id = "org.cloudfoundry.springboot",                version = "1.0.120", optional = true },
  { id = "org.cloudfoundry.distzip",                   version = "1.0.108", optional = true },
  { id = "org.cloudfoundry.procfile",                  version = "1.0.44", optional = true },

### Order does not matter
  { id = "org.cloudfoundry.azureapplicationinsights",  version = "1.0.112", optional = true },
  { id = "org.cloudfoundry.debug",                     version = "1.0.113", optional = true },
  { id = "org.cloudfoundry.googlestackdriver",         version = "1.0.61", optional = true },
  { id = "org.cloudfoundry.jdbc",                      version = "1.0.116", optional = true },
  { id = "org.cloudfoundry.jmx",                       version = "1.0.114", optional = true },
  { id = "org.cloudfoundry.springautoreconfiguration", version = "1.0.121", optional = true },
]

[stack]
id          = "io.buildpacks.stacks.bionic"
build-image = "cloudfoundry/build:base-cnb"
run-image   = "cloudfoundry/run:base-cnb"

[[metadata.dependencies]]
id      = "org.cloudfoundry.azureapplicationinsights"
name    = "Cloud Foundry Azure Application Insights Buildpack"
version = "1.0.112"
uri     = "https://storage.googleapis.com/cnb-buildpacks/azure-application-insights-cnb/org.cloudfoundry.azureapplicationinsights-1.0.112.tgz"
sha256  = "a21a1add4adfa56a79e12923ab72a270cb0aa018485c4e4b87393b1b35a5ab03"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/azure-application-insights-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.buildsystem"
name    = "Cloud Foundry Build System Buildpack"
version = "1.0.143"
uri     = "https://storage.googleapis.com/cnb-buildpacks/build-system-cnb/org.cloudfoundry.buildsystem-1.0.143.tgz"
sha256  = "3e5cb2e46975634cd2e966c031d8180f70a57b717abd3a0382e50e278048804b"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/build-system-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.debug"
name    = "Cloud Foundry Debug Buildpack"
version = "1.0.113"
uri     = "https://storage.googleapis.com/cnb-buildpacks/debug-cnb/org.cloudfoundry.debug-1.0.113.tgz"
sha256  = "3a3a93e4ec31553599c04147466902bfdd82fceed69a1a42ccd1139791215478"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/debug-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.distzip"
name    = "Cloud Foundry DistZip Buildpack"
version = "1.0.108"
uri     = "https://storage.googleapis.com/cnb-buildpacks/dist-zip-cnb/org.cloudfoundry.distzip-1.0.108.tgz"
sha256  = "a176f31bc6f31a8cee5e52cef7b6977c643b65f409b2c1bcd7bdb5efd5a61c0d"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/dist-zip-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.googlestackdriver"
name    = "Cloud Foundry Google Stackdriver Buildpack"
version = "1.0.61"
uri     = "https://storage.googleapis.com/cnb-buildpacks/google-stackdriver-cnb/org.cloudfoundry.googlestackdriver-1.0.61.tgz"
sha256  = "3909045ed86c33ac838d5a0c43a41bb7ba9abb1796dea5da501e50d5a63e97e1"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/google-stackdriver-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jdbc"
name    = "Cloud Foundry JDBC Buildpack"
version = "1.0.116"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jdbc-cnb/org.cloudfoundry.jdbc-1.0.116.tgz"
sha256  = "1ed06c9a6cd0180368a514b450a666862d6a8292fe1615e607a2f679f071e801"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jdbc-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jmx"
name    = "Cloud Foundry JMX Buildpack"
version = "1.0.114"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jmx-cnb/org.cloudfoundry.jmx-1.0.114.tgz"
sha256  = "194c82ae24a9b0f19d3b5db294093d267e9aaf653d486ef2f2625c8737916641"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jmx-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jvmapplication"
name    = "Cloud Foundry JVM Application Buildpack"
version = "1.0.87"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jvm-application-cnb/org.cloudfoundry.jvmapplication-1.0.87.tgz"
sha256  = "1112c8012ed2224346ad73d5f1a1e6bd16d34819f5977cbb5df6a9fc7836c0a5"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jvm-application-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.openjdk"
name    = "Cloud Foundry OpenJDK Buildpack"
version = "1.0.61"
uri     = "https://storage.googleapis.com/cnb-buildpacks/openjdk-cnb/org.cloudfoundry.openjdk-1.0.61.tgz"
sha256  = "eb1cda5ea138a574e66db6f87be63c9bd2106fcb0e08f7159d1a77da64bd30a9"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/openjdk-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.procfile"
name    = "Cloud Foundry Procfile Buildpack"
version = "1.0.44"
uri     = "https://storage.googleapis.com/cnb-buildpacks/procfile-cnb/org.cloudfoundry.procfile-1.0.44.tgz"
sha256  = "9b09edb08fcfccb4266b4ba3924a92bbf188bd0506770ff1c2c5fe2f68480d33"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/procfile-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.springautoreconfiguration"
name    = "Cloud Foundry Spring Auto-reconfiguration Buildpack"
version = "1.0.121"
uri     = "https://storage.googleapis.com/cnb-buildpacks/spring-auto-reconfiguration-cnb/org.cloudfoundry.springautoreconfiguration-1.0.121.tgz"
sha256  = "1df73e3fa0d5a3d3634a933cd583702a5862a2a7a7d0ddc27d3676d7fa01bf07"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/spring-auto-reconfiguration-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.springboot"
name    = "Cloud Foundry Spring Boot Buildpack"
version = "1.0.120"
uri     = "https://storage.googleapis.com/cnb-buildpacks/spring-boot-cnb/org.cloudfoundry.springboot-1.0.120.tgz"
sha256  = "2a9c389625451b60fe96ca0e38d97529042a4d98e85bda7f6becb72eeb251942"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/spring-boot-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.tomcat"
name    = "Cloud Foundry Tomcat Buildpack"
version = "1.1.33"
uri     = "https://storage.googleapis.com/cnb-buildpacks/tomcat-cnb/org.cloudfoundry.tomcat-1.1.33.tgz"
sha256  = "b7f7ea6986dfb6ddd0874ba962ee81317a05f4111fe5096d96353bcdaeb53913"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/tomcat-cnb/blob/master/LICENSE"

[metadata]
include_files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "buildpack.toml",
]
