# Copyright 2018-2019 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.2"

[buildpack]
id      = "org.cloudfoundry.java"
name    = "Cloud Foundry Java Buildpack"
version = "{{.Version}}"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[order]]
group = [

### Order is strictly enforced
  { id = "org.cloudfoundry.archiveexpanding",          version = "1.0.30", optional = true },
  { id = "org.cloudfoundry.openjdk",                   version = "1.0.15" },
  { id = "org.cloudfoundry.buildsystem",               version = "1.0.31", optional = true },
  { id = "org.cloudfoundry.jvmapplication",            version = "1.0.22" },

### Order determines precedence
  { id = "org.cloudfoundry.tomcat",                    version = "1.0.34", optional = true },
  { id = "org.cloudfoundry.springboot",                version = "1.0.27", optional = true },
  { id = "org.cloudfoundry.distzip",                   version = "1.0.27", optional = true },
  { id = "org.cloudfoundry.procfile",                  version = "1.0.11", optional = true },

### Order does not matter
  { id = "org.cloudfoundry.azureapplicationinsights",  version = "1.0.29", optional = true },
  { id = "org.cloudfoundry.debug",                     version = "1.0.29", optional = true },
  { id = "org.cloudfoundry.googlestackdriver",         version = "1.0.22", optional = true },
  { id = "org.cloudfoundry.jdbc",                      version = "1.0.30", optional = true },
  { id = "org.cloudfoundry.jmx",                       version = "1.0.28", optional = true },
  { id = "org.cloudfoundry.springautoreconfiguration", version = "1.0.32", optional = true },
]

[[metadata.dependencies]]
id      = "org.cloudfoundry.archiveexpanding"
name    = "Cloud Foundry Archive Expanding Buildpack"
version = "1.0.30"
uri     = "https://storage.googleapis.com/cnb-buildpacks/archive-expanding-cnb/org.cloudfoundry.archiveexpanding-1.0.30.tgz"
sha256  = "bb8a6116df973c6f017b3904eda6ed5b09a80cb41979311d6c261e169e0b9319"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/archive-expanding-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.azureapplicationinsights"
name    = "Cloud Foundry Azure Application Insights Buildpack"
version = "1.0.29"
uri     = "https://storage.googleapis.com/cnb-buildpacks/azure-application-insights-cnb/org.cloudfoundry.azureapplicationinsights-1.0.29.tgz"
sha256  = "79f07555178e844887eb064c0007e17d47af7579b02d0122d6d3dad4118f170e"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/azure-application-insights-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.buildsystem"
name    = "Cloud Foundry Build System Buildpack"
version = "1.0.31"
uri     = "https://storage.googleapis.com/cnb-buildpacks/build-system-cnb/org.cloudfoundry.buildsystem-1.0.31.tgz"
sha256  = "4c38d58e1bced4a83c0c9b91bb8d3af9c7a008482c5ef0967baa3ba04affd913"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/build-system-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.debug"
name    = "Cloud Foundry Debug Buildpack"
version = "1.0.29"
uri     = "https://storage.googleapis.com/cnb-buildpacks/debug-cnb/org.cloudfoundry.debug-1.0.29.tgz"
sha256  = "85fc6f38fe490dbbf91e5e7cb47bb1d4468fa54ca1358ab5ac8034c7e9fb7087"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/debug-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.distzip"
name    = "Cloud Foundry DistZip Buildpack"
version = "1.0.27"
uri     = "https://storage.googleapis.com/cnb-buildpacks/dist-zip-cnb/org.cloudfoundry.distzip-1.0.27.tgz"
sha256  = "5030d5b4e514c30d3639f96a629b4239cbbb57cb1041709831768cb88c6c8635"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/dist-zip-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.googlestackdriver"
name    = "Cloud Foundry Google Stackdriver Buildpack"
version = "1.0.22"
uri     = "https://storage.googleapis.com/cnb-buildpacks/google-stackdriver-cnb/org.cloudfoundry.googlestackdriver-1.0.22.tgz"
sha256  = "dfe075c4fa5a4a1d4789df7ab9853223837cafad20c9c48a7bef8d9aa4fcfd9a"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/google-stackdriver-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jdbc"
name    = "Cloud Foundry JDBC Buildpack"
version = "1.0.30"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jdbc-cnb/org.cloudfoundry.jdbc-1.0.30.tgz"
sha256  = "2bef9de86fd8e200a124c1f4a9b0fccae7eb1fb0e12cdc6ad89600c9625e3ac0"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jdbc-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jmx"
name    = "Cloud Foundry JMX Buildpack"
version = "1.0.28"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jmx-cnb/org.cloudfoundry.jmx-1.0.28.tgz"
sha256  = "c102df5a3c89d683cb42f8ceda9c9d8031fb28eff313e6e1198489a99a23fa23"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jmx-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.jvmapplication"
name    = "Cloud Foundry JVM Application Buildpack"
version = "1.0.22"
uri     = "https://storage.googleapis.com/cnb-buildpacks/jvm-application-cnb/org.cloudfoundry.jvmapplication-1.0.22.tgz"
sha256  = "99bc73d3309ed329cbf0d7ef758cd719ee6858405faa771576b2471f3602ef78"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jvm-application-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.openjdk"
name    = "Cloud Foundry OpenJDK Buildpack"
version = "1.0.15"
uri     = "https://storage.googleapis.com/cnb-buildpacks/openjdk-cnb/org.cloudfoundry.openjdk-1.0.15.tgz"
sha256  = "8b5cd89c8522c23c7f6e99563d2e72486ee06a541628d525386ebb82a56bcf6a"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/openjdk-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.procfile"
name    = "Cloud Foundry Procfile Buildpack"
version = "1.0.11"
uri     = "https://storage.googleapis.com/cnb-buildpacks/procfile-cnb/org.cloudfoundry.procfile-1.0.11.tgz"
sha256  = "903287cf74de312d3ce465353735edbb7d30454cb3437ef3ba6d57d73206d0cc"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/procfile-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.springautoreconfiguration"
name    = "Cloud Foundry Spring Auto-reconfiguration Buildpack"
version = "1.0.32"
uri     = "https://storage.googleapis.com/cnb-buildpacks/spring-auto-reconfiguration-cnb/org.cloudfoundry.springautoreconfiguration-1.0.32.tgz"
sha256  = "fb3bb4ebd2fdb74f409155cca52b17aa69d8fc19fff1146df942c3f713eff692"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/spring-auto-reconfiguration-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.springboot"
name    = "Cloud Foundry Spring Boot Buildpack"
version = "1.0.27"
uri     = "https://storage.googleapis.com/cnb-buildpacks/spring-boot-cnb/org.cloudfoundry.springboot-1.0.27.tgz"
sha256  = "4978a20f52110dfeeb4bab38e34a7178ba75e4b0fcd510f1de6b126e02ad5964"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/spring-boot-cnb/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "org.cloudfoundry.tomcat"
name    = "Cloud Foundry Tomcat Buildpack"
version = "1.0.34"
uri     = "https://storage.googleapis.com/cnb-buildpacks/tomcat-cnb/org.cloudfoundry.tomcat-1.0.34.tgz"
sha256  = "44e2d2ab14222277bb073d333fde7010a4b8a1162fb85e0f8f40517aef7760dd"
stacks  = [ "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/tomcat-cnb/blob/master/LICENSE"

[metadata]
include_files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "buildpack.toml",
]
