---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: build-system-buildpack
- name: java-buildpack-group
- name: jvm-application-buildpack
- name: openjdk-buildpack
- name: pack

run:
  path: java-buildpack-group/ci/build.sh
