---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: azure-application-insights-buildpack-artifactory
- name: build-system-buildpack-artifactory
- name: debug-buildpack-artifactory
- name: google-stackdriver-buildpack-artifactory
- name: java-buildpack-group
- name: jmx-buildpack-artifactory
- name: jvm-application-buildpack-artifactory
- name: openjdk-buildpack-artifactory
- name: procfile-buildpack-artifactory

outputs:
- name: artifactory

run:
  path: java-buildpack-group/ci/package.sh

params:
  VERSION: 1.0.0-BUILD-SNAPSHOT
