---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu
    tag: latest

inputs:
- name: archive-expanding-cnb-artifactory
- name: azure-application-insights-cnb-artifactory
- name: build-system-cnb-artifactory
- name: debug-cnb-artifactory
- name: dist-zip-cnb-artifactory
- name: google-stackdriver-cnb-artifactory
- name: java-buildpack-group
- name: jdbc-cnb-artifactory
- name: jmx-cnb-artifactory
- name: jvm-application-cnb-artifactory
- name: openjdk-cnb-artifactory
- name: procfile-cnb-artifactory
- name: spring-auto-reconfiguration-cnb-artifactory
- name: spring-boot-cnb-artifactory
- name: tomcat-cnb-artifactory

outputs:
- name: artifactory

run:
  path: java-buildpack-group/ci/package.sh

params:
  VERSION: 1.0.0-BUILD-SNAPSHOT
