---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/java-buildpack-group
    tag: latest

inputs:
- name: build-system-buildpack-artifactory
- name: java-buildpack-group
- name: jvm-application-buildpack-artifactory
- name: openjdk-buildpack-artifactory

run:
  path: java-buildpack-group/ci/package.sh
